# Default values for flask-app.
replicaCount: 1

image:
  repository: naumov94/flask-demo-app
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

containerPort: 5000

serviceAccount:
  create: false

ingress:
  enabled: false

autoscaling:
  enabled: false
